# -*- coding: utf-8 -*-
"""Clase 8/6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3AYyEf9Q5JzhYMrJuvVOgolr_e_l-ZE
"""

# ==================================================
# INSTALACIÓN DE LIBRERÍAS
# ==================================================

!pip install -q kagglehub
!pip install -q pandas
!pip install -q numpy
!pip install -q scikit-learn
!pip install -q transformers
!pip install -q torch

# ==================================================
# DESCARGA DEL DATASET DESDE KAGGLE
# ==================================================

import kagglehub

# Descarga automática del dataset
path = kagglehub.dataset_download(
    "blastchar/telco-customer-churn"
)

print("Dataset descargado en:")
print(path)

# ==================================================
# CARGA DEL DATASET
# ==================================================

import pandas as pd
import os

# Mostrar archivos disponibles
print(os.listdir(path))

# Cargar CSV
df = pd.read_csv(
    os.path.join(
        path,
        "WA_Fn-UseC_-Telco-Customer-Churn.csv"
    )
)

print("Dimensiones:", df.shape)

df.head()

# ==================================================
# ANÁLISIS INICIAL
# ==================================================

print(df.info())

print("\nValores nulos:")
print(df.isnull().sum())

print("\nDistribución de la variable objetivo:")
print(df["Churn"].value_counts())

# ==================================================
# AGENTE 1
# NORMALIZADOR
# ==================================================

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

class AgenteNormalizador:

    def __init__(self):
        self.scaler = StandardScaler()

    def procesar(self, df):

        datos = df.copy()

        print("Iniciando limpieza...")

        # Eliminar identificador
        datos.drop("customerID", axis=1, inplace=True)

        # Convertir TotalCharges a numérico
        datos["TotalCharges"] = pd.to_numeric(
            datos["TotalCharges"],
            errors="coerce"
        )

        # Imputar valores faltantes
        datos["TotalCharges"].fillna(
            datos["TotalCharges"].median(),
            inplace=True
        )

        # Codificación categórica
        le = LabelEncoder()

        for columna in datos.columns:

            if datos[columna].dtype == "object":

                datos[columna] = le.fit_transform(
                    datos[columna]
                )

        # Separar variables
        X = datos.drop("Churn", axis=1)

        y = datos["Churn"]

        # Escalado
        X = self.scaler.fit_transform(X)

        # División entrenamiento/prueba
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.2,
            random_state=42,
            stratify=y
        )

        print("Normalización completada")

        return X_train, X_test, y_train, y_test

# ==================================================
# EJECUCIÓN DEL AGENTE 1
# ==================================================

agente1 = AgenteNormalizador()

X_train, X_test, y_train, y_test = agente1.procesar(df)

print(X_train.shape)
print(X_test.shape)

# ==================================================
# AGENTE 2
# ENTRENADOR DE MODELOS
# ==================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

class AgenteEntrenador:

    def entrenar(
        self,
        X_train,
        X_test,
        y_train,
        y_test
    ):

        modelos = {

            "Random Forest":
                RandomForestClassifier(
                    n_estimators=200,
                    random_state=42
                ),

            "Logistic Regression":
                LogisticRegression(
                    max_iter=300
                )
        }

        mejor_modelo = None
        mejor_f1 = 0

        resultados = {}

        for nombre, modelo in modelos.items():

            print(f"\nEntrenando {nombre}")

            modelo.fit(
                X_train,
                y_train
            )

            pred = modelo.predict(
                X_test
            )

            accuracy = accuracy_score(
                y_test,
                pred
            )

            precision = precision_score(
                y_test,
                pred
            )

            recall = recall_score(
                y_test,
                pred
            )

            f1 = f1_score(
                y_test,
                pred
            )

            resultados[nombre] = {

                "accuracy": accuracy,
                "precision": precision,
                "recall": recall,
                "f1": f1
            }

            if f1 > mejor_f1:

                mejor_f1 = f1
                mejor_modelo = nombre

        return resultados, mejor_modelo

# ==================================================
# EJECUCIÓN DEL AGENTE 2
# ==================================================

agente2 = AgenteEntrenador()

metricas, mejor_modelo = agente2.entrenar(
    X_train,
    X_test,
    y_train,
    y_test
)

print("\nMejor modelo:")
print(mejor_modelo)

print("\nMétricas:")
print(metricas)

import transformers

print(transformers.__version__)

# ==================================================
# CARGA DEL TRANSFORMER (FLAN-T5)
# ==================================================

from transformers import AutoTokenizer
from transformers import AutoModelForSeq2SeqLM

modelo_id = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(
    modelo_id
)

modelo = AutoModelForSeq2SeqLM.from_pretrained(
    modelo_id
)

print("Transformer cargado correctamente")

# ==================================================
# AGENTE 3
# COMUNICADOR
# ==================================================

class AgenteComunicador:

    def __init__(self, generador):

        self.generador = generador

    def generar_reporte(
        self,
        metricas,
        mejor_modelo
    ):

        datos = metricas[mejor_modelo]

        prompt = f"""
        Genera un reporte académico breve.

        Modelo seleccionado:
        {mejor_modelo}

        Accuracy:
        {datos['accuracy']:.3f}

        Precision:
        {datos['precision']:.3f}

        Recall:
        {datos['recall']:.3f}

        F1:
        {datos['f1']:.3f}

        Explica los resultados en lenguaje natural.
        """

        respuesta = self.generador(
            prompt,
            max_new_tokens=200
        )

        return respuesta[0]["generated_text"]

# ==================================================
# EJECUCIÓN DEL AGENTE 3
# COMUNICADOR
# ==================================================

import torch

class AgenteComunicador:

    def __init__(self, tokenizer, modelo):
        self.tokenizer = tokenizer
        self.modelo = modelo

    def generar_reporte(self, metricas, mejor_modelo):

        datos = metricas[mejor_modelo]

        prompt = f"""
        Generate a brief academic report in Spanish.

        Selected model: {mejor_modelo}
        Accuracy: {datos['accuracy']:.3f}
        Precision: {datos['precision']:.3f}
        Recall: {datos['recall']:.3f}
        F1 Score: {datos['f1']:.3f}

        Explain the results in natural language.
        """

        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=512
        )

        with torch.no_grad():
            outputs = self.modelo.generate(
                **inputs,
                max_new_tokens=200,
                num_beams=4,
                early_stopping=True
            )

        respuesta = self.tokenizer.decode(
            outputs[0],
            skip_special_tokens=True
        )

        return respuesta


# Instanciar y ejecutar
agente3 = AgenteComunicador(tokenizer, modelo)

reporte = agente3.generar_reporte(
    metricas,
    mejor_modelo
)

print("=" * 50)
print("REPORTE GENERADO POR EL AGENTE COMUNICADOR")
print("=" * 50)
print(reporte)

# ==================================================
# PIPELINE COMPLETO
# ORQUESTADOR DE LOS 3 AGENTES
# ==================================================

def pipeline_completo(df):

    print("=" * 50)
    print("INICIANDO PIPELINE MULTIAGENTE")
    print("=" * 50)

    # --- AGENTE 1: Normalización ---
    print("\n[AGENTE 1] Normalizando datos...")

    agente1 = AgenteNormalizador()

    X_train, X_test, y_train, y_test = agente1.procesar(df)

    print(f"  Train: {X_train.shape} | Test: {X_test.shape}")

    # --- AGENTE 2: Entrenamiento ---
    print("\n[AGENTE 2] Entrenando modelos...")

    agente2 = AgenteEntrenador()

    metricas, mejor_modelo = agente2.entrenar(
        X_train,
        X_test,
        y_train,
        y_test
    )

    print(f"\n  Mejor modelo seleccionado: {mejor_modelo}")

    for nombre, vals in metricas.items():
        print(f"\n  {nombre}:")
        for metrica, valor in vals.items():
            print(f"    {metrica}: {valor:.4f}")

    # --- AGENTE 3: Comunicación ---
    print("\n[AGENTE 3] Generando reporte con Transformer...")

    # Sin pipeline, directo con tokenizer y modelo
    agente3 = AgenteComunicador(tokenizer, modelo)

    reporte = agente3.generar_reporte(
        metricas,
        mejor_modelo
    )

    print("\n" + "=" * 50)
    print("REPORTE FINAL")
    print("=" * 50)
    print(reporte)

    return {
        "metricas": metricas,
        "mejor_modelo": mejor_modelo,
        "reporte": reporte
    }


# Ejecutar pipeline completo
resultado = pipeline_completo(df)