# -*- coding: utf-8 -*-
"""Clase 15/6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QPwRq96mysc1ckiUjz5ty7VQ55DKEaUB
"""

# ==================================================
# INSTALACIÓN DE LIBRERÍAS
# ==================================================

!pip install -q kagglehub
!pip install -q pandas
!pip install -q numpy
!pip install -q scikit-learn
!pip install -q transformers
!pip install -q torch

# ==================================================
# DESCARGA DEL DATASET DESDE KAGGLE
# ==================================================

import kagglehub

# Descarga automática del dataset
path = kagglehub.dataset_download(
    "blastchar/telco-customer-churn"
)

print("Dataset descargado en:")
print(path)

# ==================================================
# CARGA DEL DATASET
# ==================================================

import pandas as pd
import os

# Mostrar archivos disponibles
print(os.listdir(path))

# Cargar CSV
df = pd.read_csv(
    os.path.join(
        path,
        "WA_Fn-UseC_-Telco-Customer-Churn.csv"
    )
)

print("Dimensiones:", df.shape)

df.head()

# ==================================================
# ANÁLISIS INICIAL
# ==================================================

print(df.info())

print("\nValores nulos:")
print(df.isnull().sum())

print("\nDistribución de la variable objetivo:")
print(df["Churn"].value_counts())

# ==================================================
# AGENTE 1
# NORMALIZADOR
# ==================================================

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

class AgenteNormalizador:

    def __init__(self):
        self.scaler = StandardScaler()

    def procesar(self, df):

        datos = df.copy()

        print("Iniciando limpieza...")

        # Eliminar identificador
        datos.drop("customerID", axis=1, inplace=True)

        # Convertir TotalCharges a numérico
        datos["TotalCharges"] = pd.to_numeric(
            datos["TotalCharges"],
            errors="coerce"
        )

        # Imputar valores faltantes
        datos["TotalCharges"].fillna(
            datos["TotalCharges"].median(),
            inplace=True
        )

        # Codificación categórica
        le = LabelEncoder()

        for columna in datos.columns:

            if datos[columna].dtype == "object":

                datos[columna] = le.fit_transform(
                    datos[columna]
                )

        # Separar variables
        X = datos.drop("Churn", axis=1)

        y = datos["Churn"]

        # Escalado
        X = self.scaler.fit_transform(X)

        # División entrenamiento/prueba
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.2,
            random_state=42,
            stratify=y
        )

        print("Normalización completada")

        return X_train, X_test, y_train, y_test

# ==================================================
# EJECUCIÓN DEL AGENTE 1
# ==================================================

agente1 = AgenteNormalizador()

X_train, X_test, y_train, y_test = agente1.procesar(df)

print(X_train.shape)
print(X_test.shape)

# ==================================================
# AGENTE 2
# ENTRENADOR DE MODELOS
# ==================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

class AgenteEntrenador:

    def entrenar(
        self,
        X_train,
        X_test,
        y_train,
        y_test
    ):

        modelos = {

            "Random Forest":
                RandomForestClassifier(
                    n_estimators=200,
                    random_state=42
                ),

            "Logistic Regression":
                LogisticRegression(
                    max_iter=300
                )
        }

        mejor_modelo = None
        mejor_f1 = 0

        resultados = {}

        for nombre, modelo in modelos.items():

            print(f"\nEntrenando {nombre}")

            modelo.fit(
                X_train,
                y_train
            )

            pred = modelo.predict(
                X_test
            )

            accuracy = accuracy_score(
                y_test,
                pred
            )

            precision = precision_score(
                y_test,
                pred
            )

            recall = recall_score(
                y_test,
                pred
            )

            f1 = f1_score(
                y_test,
                pred
            )

            resultados[nombre] = {

                "accuracy": accuracy,
                "precision": precision,
                "recall": recall,
                "f1": f1
            }

            if f1 > mejor_f1:

                mejor_f1 = f1
                mejor_modelo = nombre

        return resultados, mejor_modelo

# ==================================================
# EJECUCIÓN DEL AGENTE 2
# ==================================================

agente2 = AgenteEntrenador()

metricas, mejor_modelo = agente2.entrenar(
    X_train,
    X_test,
    y_train,
    y_test
)

print("\nMejor modelo:")
print(mejor_modelo)

print("\nMétricas:")
print(metricas)

import transformers

print(transformers.__version__)

# ==================================================
# CARGA DEL TRANSFORMER (FLAN-T5)
# ==================================================

from transformers import AutoTokenizer
from transformers import AutoModelForSeq2SeqLM

modelo_id = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(
    modelo_id
)

modelo = AutoModelForSeq2SeqLM.from_pretrained(
    modelo_id
)

print("Transformer cargado correctamente")

# ==================================================
# AGENTE 3
# COMUNICADOR (REPORTE + CHAT INTERACTIVO)
# ==================================================

import torch

class AgenteComunicador:

    def __init__(self, tokenizer, modelo, df=None, metricas=None, mejor_modelo=None):
        self.tokenizer = tokenizer
        self.modelo = modelo
        self.contexto_dataset = ""
        self.contexto_metricas = ""

        if df is not None and metricas is not None and mejor_modelo is not None:
            self._construir_contexto(df, metricas, mejor_modelo)

    def _construir_contexto(self, df, metricas, mejor_modelo):

        datos_mejor = metricas[mejor_modelo]

        churn_counts = df['Churn'].value_counts().to_dict()

        self.contexto_dataset = (
            f"This dataset has {df.shape[0]} rows and {df.shape[1]} columns. "
            f"Customers who churned (Yes): {churn_counts.get('Yes', 0)}. "
            f"Customers who stayed (No): {churn_counts.get('No', 0)}. "
            f"Columns: {', '.join(df.columns.tolist())}."
        )

        self.contexto_metricas = (
            f"The best model is {mejor_modelo} with "
            f"accuracy {datos_mejor['accuracy']:.3f}, "
            f"precision {datos_mejor['precision']:.3f}, "
            f"recall {datos_mejor['recall']:.3f}, "
            f"and F1 score {datos_mejor['f1']:.3f}."
        )

    def _generar(self, prompt, max_new_tokens=200, num_beams=4):

        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=512
        )

        with torch.no_grad():
            outputs = self.modelo.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                num_beams=num_beams,
                early_stopping=(num_beams > 1)
            )

        return self.tokenizer.decode(
            outputs[0],
            skip_special_tokens=True
        )

    def generar_reporte(self, metricas, mejor_modelo):

        datos = metricas[mejor_modelo]

        prompt = f"""
        Generate a brief academic report in Spanish.

        Selected model: {mejor_modelo}
        Accuracy: {datos['accuracy']:.3f}
        Precision: {datos['precision']:.3f}
        Recall: {datos['recall']:.3f}
        F1 Score: {datos['f1']:.3f}

        Explain the results in natural language.
        """

        return self._generar(prompt, max_new_tokens=200)

    def responder_pregunta(self, pregunta):

        pregunta_lower = pregunta.lower()

        if any(k in pregunta_lower for k in ["fila", "columna", "dataset", "churn", "abandon", "cliente"]):
            contexto_usar = self.contexto_dataset
        elif any(k in pregunta_lower for k in ["modelo", "accuracy", "precision", "recall", "f1", "metrica", "métrica"]):
            contexto_usar = self.contexto_metricas
        else:
            contexto_usar = self.contexto_dataset + " " + self.contexto_metricas

        prompt = f"""Answer the question using only the information below.

Information:
{contexto_usar}

Question: {pregunta}
Answer:"""

        return self._generar(prompt, max_new_tokens=80, num_beams=1)

    def chat_interactivo(self):

        print("=" * 50)
        print("CHAT INTERACTIVO - PREGUNTAS SOBRE EL CONTEXTO")
        print("Escribí 'salir' para terminar")
        print("=" * 50)

        while True:

            pregunta = input("\nTu pregunta: ")

            if pregunta.lower().strip() == "salir":
                print("Chat finalizado.")
                break

            respuesta = self.responder_pregunta(pregunta)

            print("Respuesta:", respuesta)

# ==================================================
# EJECUCIÓN DEL AGENTE 3
# COMUNICADOR
# ==================================================

agente3 = AgenteComunicador(
    tokenizer,
    modelo,
    df=df,
    metricas=metricas,
    mejor_modelo=mejor_modelo
)

# Reporte automático
reporte = agente3.generar_reporte(
    metricas,
    mejor_modelo
)

print("=" * 50)
print("REPORTE GENERADO POR EL AGENTE COMUNICADOR")
print("=" * 50)
print(reporte)

# Chat interactivo
agente3.chat_interactivo()

# ==================================================
# PIPELINE COMPLETO
# ORQUESTADOR DE LOS 3 AGENTES
# ==================================================

def pipeline_completo(df):

    print("=" * 50)
    print("INICIANDO PIPELINE MULTIAGENTE")
    print("=" * 50)

    # --- AGENTE 1: Normalización ---
    print("\n[AGENTE 1] Normalizando datos...")

    agente1 = AgenteNormalizador()

    X_train, X_test, y_train, y_test = agente1.procesar(df)

    print(f"  Train: {X_train.shape} | Test: {X_test.shape}")

    # --- AGENTE 2: Entrenamiento ---
    print("\n[AGENTE 2] Entrenando modelos...")

    agente2 = AgenteEntrenador()

    metricas, mejor_modelo = agente2.entrenar(
        X_train,
        X_test,
        y_train,
        y_test
    )

    print(f"\n  Mejor modelo seleccionado: {mejor_modelo}")

    for nombre, vals in metricas.items():
        print(f"\n  {nombre}:")
        for metrica, valor in vals.items():
            print(f"    {metrica}: {valor:.4f}")

    # --- AGENTE 3: Comunicación ---
    print("\n[AGENTE 3] Generando reporte con Transformer...")

    agente3 = AgenteComunicador(
        tokenizer,
        modelo,
        df=df,
        metricas=metricas,
        mejor_modelo=mejor_modelo
    )

    reporte = agente3.generar_reporte(
        metricas,
        mejor_modelo
    )

    print("\n" + "=" * 50)
    print("REPORTE FINAL")
    print("=" * 50)
    print(reporte)

    # Chat interactivo opcional
    agente3.chat_interactivo()

    return {
        "metricas": metricas,
        "mejor_modelo": mejor_modelo,
        "reporte": reporte
    }


# Ejecutar pipeline completo
resultado = pipeline_completo(df)